### ISSUE TITLE
Symlink loops cause infinite recursion

### ISSUE THREAD

**Issue by rasteric** [karrick/godirwalk#11]
When symlinks are followed godirwalk may enter an infinite loop. A standard Linux installation can have these types of symlinks that create a directory loop, my Linux Mint machine certainly contains them out of the box.

As a result godirwalk will never end on some systems if FollowSymbolicLinks is true.

**Comment by jdnurmi** [comment]
To add to this, not all filesystems properly report the symlink permissions during a ReadDir call (xfs with the default options, it seems), so even when FollowSymbolicLinks is false, in some cases you still have to do an additional LStat to determine if entries are symlinks anyhow, which is unfortunate, but not insurmountable.

**Comment by chadnetzer** [comment]
@rasteric Do you have an example that actually enters an infinite recursion?  I've done some non-exhaustive testing on this issue, and in cases where directory loops made with symbolic links are using absolute paths, the OS eventually returns an error on the Stat() call due to it's own symbolic link loop protection.  Linux apparently allows ~40 levels of symbolic links in a path, MacOS ~20.

When using relative symbolic links to make a directory loop (ie. in the testdata dir, there is 'testdata/symlinks/dir-symlink', which contains '../../testdata' as a referent), it can actually fail sooner, because the line that Join()s the path.Dir() to the symlink referent ends up building an invalid path after the first loop.  The Walk() keeps track of the directory paths by using the symlink name for the directory, rather than the symlink referent name, so eventually the Dir() path becomes invalid.

However, if the symlink name is the same as the referent directory name, then the loop works, and again eventually the OS aborts with an error after finding too many symlinks in a path lookup. ie.:

```
mkdir -p testdata2
cd testdata2
ln -s ../testdata2 testdata2
```
will create such a loop (which will then error out when the walk reaches the max symlink depth).

In any case, there does seem to be OS protection against denial-of-service by creating a symlink loop.  The standard approach to ensure that a loop is not entered at all seems to be to create a set of directory (dev/ino) pairs already visited, and skip any already seen dirs.  The set can be updated as the walk progresses, removing entries after a directory tree has been processed, so the space impact should be fairly minimal.  But it seems like it could involve some restructuring of the internals, especially to support both Unix and Windows.

**Comment by rasteric** [comment]
Hi! No I don't have an example, all I can say is that godirwalk stalls (does not terminate) when I run it over my whole file system which also included a mounted NTFS volume. I was suspecting that this may be caused by symlinks, because it only occurs when FollowSymbolicLinks is true and filepath.Walk does terminate when I run it over the same directory. It could also be a concurrency issue or something related to special files or permissions, for instance.

Sorry I can't be more specific, in my tests godirwalk worked fine for smaller directories but fails on very large ones when the option is enabled. It *does* work on the same directory when the option is not enabled.

**Comment by chadnetzer** [comment]
@jdnurmi Current code (see readdir_unix.go) handles the case of filesystems not returning file type bits in readdir dtype, by doing an os.Stat(), *not* os.Lstat(), on the pathname.  This seems incorrect. 
 As you suggest, it seems like Lstat() should be the proper call in such cases; otherwise on such filesystems, the files returned to walk() would never have the symlink bit set (?).

To test this, I built an XFS filesystem on Centos 7 with the 'ftype' and 'crc' options set to 0, which changes to readdir behavior to not report the file type, and as expected, the TestReadDirentsSymlinks and TestWalkFollowSymbolicLinksFalse tests fail on that filesystem.  However, if I change Stat() to Lstat() in readdir_unix.go, the tests succeed.  I'll do a bit more testing, and open an issue/PR.

Thanks for bringing this up, this might have serious implications for a tool I wrote, so I'm going to look into it further.  BTW, since the CRC option for Centos 7 is (as-of late 2016) now default during creation.  But that likely leaves a fair amount of RHEL/Centos 7 XFS filesystems affected by this behavior.

**Comment by chadnetzer** [comment]
@rasteric Thanks for the info.  I will hopefully look into this further in the coming weeks and may follow up with you further to see if you are willing to help test some changes.  Just to be clear, you found this on a Linux (Mint) system, with an NTFS mount?  Was your Linux filesystem ext4, or something else?

**Comment by karrick** [comment]
@chadnetzer, I think you're correct that it should be calling `os.Lstat()` rather than `os.Stat()` when it cannot ascertain the file mode bits returned by the OS's readdir.

**Comment by karrick** [comment]
@rasteric and @jdnurmi, thanks for reporting and adding insight to this issue.

I have pushed v1.7.4 with the fix recommended by @chadnetzer to invoke `Lstat` rather than `Stat` when it gets ambiguous file mode bits from the OS.

One of the reasons that `filepath.Walk` terminates on a filesystem with heavy symbolic link usage is that it does not handle symbolic links. As @rasteric discovered and mentioned above, turning off `FollowSymbolicLinks` allowed it to terminate before this update. So the error is clearly scoped to a call to `Stat` when it should be calling `Lstat`.

This update fixes the problem on the test data set brought up above, but I have not tested it in your environment. *Please* get back with me about whether this addresses the problems you observed on your system.

**Comment by chadnetzer** [comment]
@karrick Can confirm v1.7.4 go tests now all pass on my XFS filesystem where readdir() returns DT_UNKNOWN.  This change should address the @jdnurmi concern (thanks to him for the comment that spurred looking into this also).  It'll be interesting to know if this also affects/solves the issue that @rasteric reported.  Finally, thanks for bumping patch number which helps w/ go.mod dependence.

**Comment by karrick** [comment]
I am going to go ahead and close this issue, as I have not received any other comments on the issue since our changes fixed the test cases on our systems.

Again, thanks all for your insights and assistance on this issue!
