### ISSUE TITLE
Don't ship testdata with the repo

### ISSUE THREAD

**Issue by neersighted** [karrick/godirwalk#17]
It would be nice if dirwalk did not ship the test scaffolding symlinks as part of the repo, but instead generated them on the fly (or with a script).

This causes minor headaches, as I will occasionally check for broken symlinks in my $HOME folder, and my local clone of scc (which depends on dirwalk) regularly turns up false positives, which I have to adjust my tools to deal with.

**Comment by karrick** [comment]
That is a really good point.

**Comment by karrick** [comment]
I'm not sure about generating the test scaffolding in a script, because the tests need to run on both UNIX like operating systems, and at least Windows.

One solution might be to ship a tiny Go source file that could be executed with `go run generate_test_scaffolding.go` which should be able to run on any of the supported operating systems.

**Comment by karrick** [comment]
Or even better, just put that code in an `init` function for a `scaffolding_test.go` file.
