### ISSUE TITLE
Get back os.Stat data on Callback

### ISSUE THREAD

**Issue by MeshyIce** [karrick/godirwalk#42]
Hi, I'm writing a very performant application that calculates file sizes.
For this reason, I would like to re-use the `os.Stat` return value that happens on every file, as this may lead to a small performance issue in my code.
Is there a way to get the `stat` struct back from the `Walk` function?
Or will I have to run `os.Stat` again?

**Comment by karrick** [comment]
This is a great question, but unfortunately `godirwalk` cannot help you with this case, because it tries to avoid calling `stat` for each file, because for most applications the type of file system entry is already available when it read the directory containing that file. So `godirwalk` reads the directory, sees `d1` with a entry type, as in `syscall.DT_DIR`, which means it is a directory, and creates the `godirwalk.Dirent` as appropriate. Or it reads `f2` with the `syscall.DT_SOCK` and knows that is is a socket.

In cases where when reading the directory entry does not tell `godirwalk` what type of file system entry a particular entry is, for example, when the directory read returns a type of `syscall.DT_UNKNOWN`, then `godirwalk` must perform a `stat` on the file system entry to learn its type.

One of the goals of this library is to _not_ make extra file system requests when not needed. Since `filepath.Walk` reads the directory, then ignores the file system type, but then stats the file, this is wasted time. This library avoids that extra call, but the user is still able to invoke `stat` as it sees fit. For instance, maybe your application only wants to calculate the sizes of regular files, then it only needs to call `stat` if the entry is a regular file to get that file size.

See this for an example: https://github.com/karrick/godirwalk/blob/master/examples/sizes/main.go#L42

**Comment by MeshyIce** [comment]
I now see that I have misunderstood how `Walk` works. This is implemented in a very good way. Thank you for the library and for your answer!
