### ISSUE TITLE
Modification time and size?

### ISSUE THREAD

**Issue by zippoxer** [karrick/godirwalk#7]
Why are these attributes not preserved from os.FileInfo into godirwalk.Dirent? Instead of selecting fields from FileInfo to bring into Dirent, couldn't we just keep FileInfo as a field in Dirent and expose it's methods?

I'm very impressed by the performance of godirwalk, but I'm developing a file tree diff algorithm and both the modification time and the size of files are crucial for it.

**Comment by karrick** [comment]
Thank you for your compliments.

Great question. When we ask the Operating System to enumerate the contents of a directory, we get some of the information back about each entry, but not all the information back. We get the entry's name and file type, but not the size and modification time. For your use case, you will still need to call `os.Stat` for each file system entry in your call back to ask the OS to return these, as your use case requires that data.

The issue is there are many applications for which that second OS call is not necessary, and that is one of the few reasons why `godirwalk` can be much faster than the runtime standard library's `filepath.Walk` call. There are other reasons it is faster, such as how `godirwalk` re-uses the same memory buffer for the entire traversal, rather than how the standard library re-allocates a new buffer _nearly_ every time it makes a call to the OS for more data.

I have written an application like yours which does need the file's modification time and size, and in the call back it invokes `os.Stat` on the entries. It is still faster than it was when the program used `filepath.Walk` however, due to the other improvements this library has.

**Comment by Owyn** [comment]
> Great question. When we ask the Operating System to enumerate the contents of a directory, we get some of the information back about each entry, but not all the information back. We get the entry's name and file type, but not the size and modification time.

is that still the case for `os.ReadDir()` ? at least on windows it uses `syscall.FindNextFile()` internally which already shows both the modtime and filesize, 

after switching to ReadDir from Walk my program dropped from many minutes of running and making weird noises on my HDD to just few seconds to read a big dir recursively and get all the modified-times
