### ISSUE TITLE
Why not submit to Go standard library?

### ISSUE THREAD

**Issue by choleraehyq** [karrick/godirwalk#9]
I think the answer should be added into readme.

**Comment by karrick** [comment]
Really great question, one about which I've thought quite a bit.

My actual reason for not doing so is inertia, and I have no idea how much energy it would take to work through the red tape of submitting a change to Go standard library, only to have it rejected because reason X.

`godirwalk` has a different API than the Go standard library directory walk function. If I submitted something, it would have to sit alongside the other library, awkwardly next to it. And I would not be happy unless I structured the update to vastly improve the performance of both the standard library, and the new library call, while obviously only the new call would be able to realize all of the benefits, because in the end there are differences between both approaches. This amount of work is unbounded.

Along with these unknowns, I have a lot of unfinished work I personally want to complete on another open source library I am trying to find time to work on.
